### ISSUE TITLE
Script fails on MacOS X

### ISSUE THREAD

**Issue by jameslbrown** [simgunz/anki-decks_common-ipa#1]
Simone, running on Mac OS X 10.11.1 I get:

./build-deck.sh
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]

Chasing the find command to:

find  -f "collection-dump.sql" | xargs zip "../Common IPA.apkg"

works:

./build-deck.sh
  adding: collection-dump.sql (deflated 75%)

But when I try to open the 'Common IPA.apkg' file Anki says:

<i>This file does not appear to be a valid .apkg file. If you're getting this error from a file downloaded from AnkiWeb, chances are that your download failed. Please try again, and if the problem persists, please try again with a different browser.</i>

Any ideas?

Thanks, James.

**Comment by simgunz** [comment]
The command should be:

find  -type f ! -name "collection-dump.sql" | xargs zip "../Italian IPA.apkg"

which means find all the "things" of type f (file, not folders) but don't include (!) the one with name matching "collection-dump.sql".

According to the manual page of find in MAC OSX it should work. Your command seems to be wrong because you are probably only including the collection-dump.sql in the zip (Can you check what is it included in the zip?) while you should include all the other files in the folder beside collection-dump.sql.

From the man page of "find" in MAC you may need to add a backslash before the exclamation mark. (!) (even tough the error seems relate to the f option).
See:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/find.1.html

**Comment by jameslbrown** [comment]
If I use that command I get:

Mac-Pro:anki-decks_common-ipa-master jlbrown$ ./build-deck.sh
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]

Full script I used is:

#!/bin/bash

cd deck
cat collection-dump.sql | sqlite3 collection.anki2
find  -type f ! -name "collection-dump.sql" | xargs zip "../Common IPA.apkg"
rm collection.anki2
cd ..

James.

**Comment by simgunz** [comment]
Try this:

find ./ -type f ! -name "collection-dump.sql" | xargs zip "../Common
IPA.apkg"

**Comment by jameslbrown** [comment]
Thanks Simone.

It ran OK:

$ ./build-deck.sh
  adding: /collection.anki2 (deflated 88%)
  adding: /media (stored 0%)

But when I double-click on the 'Common IPA.apkg' file Anki give the "This file does not appear to be a valid .apkg file.” error I was getting before.

 James.

**Comment by simgunz** [comment]
Try to rename the file to give it a .zip extension and open it. Inside you
should see two files: "media" and "collection.anki". They should not be
into subfolders, but they should be in the root of the archive.

**Comment by jameslbrown** [comment]
Yes, the two files are in the archive. 

James.

**Comment by simgunz** [comment]
Can you try to import the package from within Anki instead of double
clicking? Can you also send me the package you generate via email so I can
test it?

**Comment by jameslbrown** [comment]
I get the same invalid .apkg message if I try Import from Anki’s File menu.

James.

**Comment by simgunz** [comment]
Send me the package by email so I can test it. You find it on my profile
page.

**Comment by simgunz** [comment]
This will fix it:

```
find ./ -type f ! -name "collection-dump.sql" | xargs zip -j "../Common IPA.apkg"
```

I've added the -j option because it seems that zip includes the absolute paths, even tough in the zip documentation it says it will only store relative paths by default.

-j
       --junk-paths
              Store just the name of a saved file (junk the path), and do  not  store  directory  names.  By
              default, zip will store the full path (relative to the current directory).
